
cluster-cancel: "scancel"
restart-times: 3
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"
max-jobs-per-second: 10
max-status-checks-per-second: 10
local-cores: 1
latency-wait: 5
use-conda: "False"
use-singularity: "False"
jobs: 500
printshellcmds: "False"

default-resources:
  runtime: 45
  mem_mb: 6000

set-threads:
  OO7_run_plast: 20
  O13_run_hmmer: 2

set-resources:
  OO7_run_plast:
    mem_mb:  64000
    runtime: 14000
  O13_run_hmmer:
    mem_mb:  128000
    runtime: 14000
